<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tianqi Ouyang">
<meta name="dcterms.date" content="2026-07-29">

<title>Ritu Project — Summary – Ritu Project – Cys-C / Creatinine Discordance in Platinum AE</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-57cb14b6d31887c86603edb388f6c431.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Ritu Project – Cys-C / Creatinine Discordance in Platinum AE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./qmd/ritu_data.html"> 
<span class="menu-text">Data Management</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./qmd/ritu_entire.html"> 
<span class="menu-text">Entire Cohort (N = 943)</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-localearly-(n--323" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Local/Early (N = 323)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-localearly-(n--323">    
        <li>
    <a class="dropdown-item" href="./qmd/ritu_whole.html">
 <span class="dropdown-text">Whole Cohort</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./qmd/ritu_carbo.html">
 <span class="dropdown-text">Carboplatin Cohort</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./qmd/ritu_carbo_auc3.html">
 <span class="dropdown-text">Carboplatin AUC ≥ 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-overview" id="toc-project-overview" class="nav-link active" data-scroll-target="#project-overview">Project Overview</a></li>
  <li><a href="#pages-and-cohort-sizes" id="toc-pages-and-cohort-sizes" class="nav-link" data-scroll-target="#pages-and-cohort-sizes">Pages and Cohort Sizes</a></li>
  <li><a href="#exclusion-flow" id="toc-exclusion-flow" class="nav-link" data-scroll-target="#exclusion-flow">Exclusion Flow</a></li>
  <li><a href="#what-changed-relative-to-the-jiaxuan-project" id="toc-what-changed-relative-to-the-jiaxuan-project" class="nav-link" data-scroll-target="#what-changed-relative-to-the-jiaxuan-project">What Changed Relative to the Jiaxuan Project</a></li>
  <li><a href="#power-caveats-localearly-pages-only" id="toc-power-caveats-localearly-pages-only" class="nav-link" data-scroll-target="#power-caveats-localearly-pages-only">Power Caveats — Local/Early pages only</a></li>
  <li><a href="#outcomes" id="toc-outcomes" class="nav-link" data-scroll-target="#outcomes">Outcomes</a>
  <ul>
  <li><a href="#grade-23-adverse-events-within-90-days" id="toc-grade-23-adverse-events-within-90-days" class="nav-link" data-scroll-target="#grade-23-adverse-events-within-90-days">Grade 2/3 Adverse Events (within 90 days)</a></li>
  <li><a href="#hospitalizations-mortality" id="toc-hospitalizations-mortality" class="nav-link" data-scroll-target="#hospitalizations-mortality">Hospitalizations &amp; Mortality</a></li>
  <li><a href="#long-horizon-kidney-outcomes-ckd-eskd-aki" id="toc-long-horizon-kidney-outcomes-ckd-eskd-aki" class="nav-link" data-scroll-target="#long-horizon-kidney-outcomes-ckd-eskd-aki">Long-Horizon Kidney Outcomes (CKD / ESKD / AKI)</a></li>
  </ul></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a></li>
  <li><a href="#key-variables" id="toc-key-variables" class="nav-link" data-scroll-target="#key-variables">Key Variables</a>
  <ul>
  <li><a href="#exposure" id="toc-exposure" class="nav-link" data-scroll-target="#exposure">Exposure</a></li>
  <li><a href="#egfr-kidney-function" id="toc-egfr-kidney-function" class="nav-link" data-scroll-target="#egfr-kidney-function">eGFR &amp; Kidney Function</a></li>
  <li><a href="#competing-risk-variables" id="toc-competing-risk-variables" class="nav-link" data-scroll-target="#competing-risk-variables">Competing Risk Variables</a></li>
  </ul></li>
  <li><a href="#reproducing" id="toc-reproducing" class="nav-link" data-scroll-target="#reproducing">Reproducing</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ritu Project — Summary</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tianqi Ouyang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="project-overview" class="level1">
<h1>Project Overview</h1>
<p>Creatinine-to-cystatin C discordance and adverse events in patients receiving platinum-based chemotherapy.</p>
<p>The project repeats the Jiaxuan analysis at <strong>two cohort levels off one pipeline</strong>: the <strong>entire cohort</strong> (N = 943, all tumour stages) and the <strong>Local/Early</strong> cohort (N = 323, advanced/metastatic patients excluded). Every exposure, model, table, figure and download is carried over unchanged at both levels; both use the newer 2022P001091 creatinine pull and carry the CKD / ESKD / AKI variable family ported from the ICI-CKD project.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Entire cohort</strong></td>
<td>no stage filter — N = 943</td>
</tr>
<tr class="even">
<td><strong>Local/Early cohort</strong></td>
<td><code>tumor_stage == "Local/Early"</code> (stage I–II / local / neoadjuvant) — N = 323</td>
</tr>
<tr class="odd">
<td><strong>Excluded from the Local/Early pages</strong></td>
<td><code>tumor_stage == "Advanced/Metastatic"</code> (stage III–IV) — 620 patients</td>
</tr>
<tr class="even">
<td><strong>Primary exposure</strong></td>
<td><code>egfr_diff_pct_per10</code> — eGFR difference (%) per 10-percentage-point decline</td>
</tr>
<tr class="odd">
<td><strong>Follow-up</strong></td>
<td>90 days from baseline sample date</td>
</tr>
<tr class="even">
<td><strong>Framework</strong></td>
<td>Competing risks (death as competing event for non-fatal outcomes)</td>
</tr>
<tr class="odd">
<td><strong>Parent project</strong></td>
<td><a href="https://tianqi-ouyang.github.io/Cys-C-project-/">Jiaxuan project</a></td>
</tr>
</tbody>
</table>
</section>
<section id="pages-and-cohort-sizes" class="level1">
<h1>Pages and Cohort Sizes</h1>
<p>The project runs at two cohort levels off the same pipeline. Both use the 2022P001091 creatinine pull and carry the full CKD / ESKD / AKI variable family.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Page</th>
<th>Cohort</th>
<th>N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./qmd/ritu_entire.html"><strong>Entire Cohort</strong></a></td>
<td>all platinum, <strong>all stages</strong></td>
<td><strong>943</strong></td>
</tr>
<tr class="even">
<td><a href="./qmd/ritu_whole.html">Whole Cohort</a></td>
<td>all platinum, Local/Early only</td>
<td><strong>323</strong></td>
</tr>
<tr class="odd">
<td><a href="./qmd/ritu_carbo.html">Carboplatin Cohort</a></td>
<td>carboplatin, Local/Early</td>
<td><strong>190</strong></td>
</tr>
<tr class="even">
<td><a href="./qmd/ritu_carbo_auc3.html">Carboplatin AUC ≥ 3</a></td>
<td>carboplatin AUC ≥ 3, Local/Early</td>
<td><strong>143</strong></td>
</tr>
</tbody>
</table>
<p>Entire cohort: 323 Local/Early + 620 Advanced/Metastatic; 596 carboplatin, 347 cisplatin. Within the 323 Local/Early: 190 carboplatin, 133 cisplatin.</p>
<p><strong><code>tumor_stage</code> differs between the two levels.</strong> It is constant in the Local/Early cohort, so it is dropped from Table 1 and from every adjuster set there. In the entire cohort it varies, so it is restored — which makes the entire-cohort page’s model specification the same as the Jiaxuan project’s, but run on the newer creatinine pull and with the kidney variables added. Comparing the two pages shows what the stage restriction does.</p>
</section>
<section id="exclusion-flow" class="level1">
<h1>Exclusion Flow</h1>
<p>Inherited from the Jiaxuan pipeline:</p>
<ol type="1">
<li>REDCap records restricted to EMPIs present in <code>N=596 for tianqi.xlsx</code> → 946</li>
<li>Patients with no matching RPDR lab records excluded (2) → 944</li>
<li>Missing baseline cystatin C (<code>cys_c_baseline</code> = NA) excluded</li>
<li>Missing platinum group (<code>platin_group</code> = NA) excluded</li>
<li>Record 911 dropped (all RPDR pre-baseline labs fall outside the 45-day window) → <strong>943 = entire cohort</strong></li>
<li><code>tumor_stage != "Local/Early"</code> excluded (620) → <strong>323 = Local/Early cohort</strong></li>
</ol>
<p><code>ritu_data.qmd</code> saves after both step 5 (<code>ritu_full_master.rds</code>) and step 6 (<code>ritu_final_master.rds</code>), so the two cohort levels come from one pipeline run and are identical in every variable definition.</p>
<p>Details in <a href="./qmd/ritu_data.html">Data Management</a>.</p>
</section>
<section id="what-changed-relative-to-the-jiaxuan-project" class="level1">
<h1>What Changed Relative to the Jiaxuan Project</h1>
<p>Four kinds of change, nothing else:</p>
<p><strong>1. Cohort source.</strong> <code>ritu_data.qmd</code> applies the stage restriction and writes <code>ritu_final_master.rds</code>; the three analysis pages read that file.</p>
<p><strong>2. <code>tumor_stage</code> dropped as a covariate.</strong> It is constant within this cohort, so it carries no information and would make the design matrix rank-deficient. It is removed from Table 1 and from the adjuster set of every Fine-Gray, cause-specific hazard, Cox PH and linear-subHR model.</p>
<p><strong>3. Two covariate fixes on the AUC ≥ 3 page only.</strong> That subgroup’s filter empties the <code>cancer_type_cat_7</code> “GI” level (0 of 143) and leaves <code>steroids</code> constant at 1 (all 143 received steroids). Together these made the design matrix rank-deficient — rank 19 of 21 — so <code>cmprsk::crr</code> failed for <em>every</em> outcome, including composite grade 2 AEs with 64 events, while the formula interface silently returned blank coefficient rows. <code>droplevels()</code> is re-applied after the cohort filter and <code>steroids</code> is dropped from that page’s adjuster sets (it stays as a descriptive Table 1 row). The whole and carboplatin cohorts are full rank throughout and keep the original adjuster set.</p>
<p><strong>4. Sparse-outcome guards.</strong> Several outcomes have very few events in 323 patients (90-day death = 2). Each model helper is wrapped so that a model which cannot be estimated emits a short note instead of aborting the render. No model specification is altered.</p>
<p>Unchanged: primary and sensitivity exposures, the <code>dose_discrep_per25increase</code> predictor in the carboplatin pages, reference categories (<code>sex</code> = Female, <code>ecog_score_cat2</code> = “0”), the competing-risks framework, Cox PH for 90-day death, eGFR capping rules, 2.5/97.5-percentile plot trimming, Word and PowerPoint downloads, and all section numbering.</p>
</section>
<section id="power-caveats-localearly-pages-only" class="level1">
<h1>Power Caveats — Local/Early pages only</h1>
<p>These follow arithmetically from the <strong>323-patient</strong> cohort and apply to the Local/Early pages. The <a href="./qmd/ritu_entire.html">entire-cohort page</a> has roughly 3× the events and is not affected in the same way — most notably 90-day death has <strong>41 events there versus 2</strong> here, so its models are worth reading on that page and not on this one.</p>
<p>The analyses are reported as specified; read the sparse ones with the event counts in view.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Events in 323</th>
<th>Multivariable estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Composite grade 2 AEs</td>
<td>149</td>
<td>adequately powered</td>
</tr>
<tr class="even">
<td>Anemia grade 2</td>
<td>138</td>
<td>adequately powered</td>
</tr>
<tr class="odd">
<td>Overall hospitalization</td>
<td>68</td>
<td>borderline</td>
</tr>
<tr class="even">
<td>Platinum-related hospitalization</td>
<td>46</td>
<td>over-parameterised</td>
</tr>
<tr class="odd">
<td>Composite grade 3 AEs</td>
<td>43</td>
<td>over-parameterised</td>
</tr>
<tr class="even">
<td>Anemia grade 3</td>
<td>40</td>
<td>over-parameterised</td>
</tr>
<tr class="odd">
<td>Thrombocytopenia grade 2</td>
<td>37</td>
<td>over-parameterised</td>
</tr>
<tr class="even">
<td>AKI (KDIGO)</td>
<td>33</td>
<td>over-parameterised</td>
</tr>
<tr class="odd">
<td>AKI grade 2</td>
<td>26</td>
<td>over-parameterised</td>
</tr>
<tr class="even">
<td>Thrombocytopenia grade 3</td>
<td>9</td>
<td>not interpretable</td>
</tr>
<tr class="odd">
<td>Individual hospitalization reasons</td>
<td>5–25</td>
<td>not interpretable</td>
</tr>
<tr class="even">
<td><strong>90-day death</strong></td>
<td><strong>2</strong></td>
<td><strong>not estimable</strong></td>
</tr>
</tbody>
</table>
<p>The multivariable models carry roughly 20 covariate degrees of freedom against a conventional target of 10 events per covariate. Univariable columns remain readable throughout.</p>
<p>Two further consequences worth stating in any write-up:</p>
<ul>
<li><strong>90-day mortality is 2/323 (0.6 %).</strong> Early-stage patients rarely die within 90 days of starting platinum — a finding in its own right, not just a limitation.</li>
<li><strong>The competing-risks correction barely bites.</strong> With death nearly absent, Fine-Gray subdistribution hazards and cause-specific hazards are close to identical in this cohort.</li>
</ul>
</section>
<section id="outcomes" class="level1">
<h1>Outcomes</h1>
<section id="grade-23-adverse-events-within-90-days" class="level2">
<h2 class="anchored" data-anchor-id="grade-23-adverse-events-within-90-days">Grade 2/3 Adverse Events (within 90 days)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Anemia grade 2</td>
<td>HGB &lt; 10 g/dL</td>
</tr>
<tr class="even">
<td>Anemia grade 3</td>
<td>HGB &lt; 8 g/dL</td>
</tr>
<tr class="odd">
<td>Thrombocytopenia grade 2</td>
<td>PLT &lt; 75 x10^9/L</td>
</tr>
<tr class="even">
<td>Thrombocytopenia grade 3</td>
<td>PLT &lt; 50 x10^9/L</td>
</tr>
<tr class="odd">
<td>AKI grade 2</td>
<td>Post-baseline CRE &gt; 1.5x pre-baseline CRE (KDIGO)</td>
</tr>
<tr class="even">
<td>AKI grade 3</td>
<td>Post-baseline CRE &gt; 3.0x pre-baseline CRE (KDIGO)</td>
</tr>
<tr class="odd">
<td>Composite grade 2</td>
<td>Any of anemia/thrombocytopenia/AKI grade 2</td>
</tr>
<tr class="even">
<td>Composite grade 3</td>
<td>Any of anemia/thrombocytopenia/AKI grade 3</td>
</tr>
</tbody>
</table>
</section>
<section id="hospitalizations-mortality" class="level2">
<h2 class="anchored" data-anchor-id="hospitalizations-mortality">Hospitalizations &amp; Mortality</h2>
<ul>
<li><strong>Hospitalizations:</strong> 11 reason categories; reasons 1–7 define <code>side_effect</code> (platinum-related)</li>
<li><strong>90-day mortality</strong> (<code>death_90</code>): derived from <code>pt_status</code> and <code>days_last_follow_up</code></li>
<li>All outcomes above censored at 90 days</li>
</ul>
</section>
<section id="long-horizon-kidney-outcomes-ckd-eskd-aki" class="level2">
<h2 class="anchored" data-anchor-id="long-horizon-kidney-outcomes-ckd-eskd-aki">Long-Horizon Kidney Outcomes (CKD / ESKD / AKI)</h2>
<p>Ported from the <a href="https://tianqi-ouyang.github.io/ICI-CKD-/data_management.html">ICI-CKD project</a>, re-anchored to <code>baseline_sample_date</code>. <strong>These are the only outcomes in the project that are not censored at 90 days</strong> — a qualifying CKD episode must be <em>sustained for ≥ 90 days</em>, so they use the full length of RPDR creatinine follow-up (median 446 days, max 1167).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Definition</th>
<th>n (%) of 323</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>aki</code></td>
<td>CRE &gt; 1.5 × median of prior 90 d, <strong>or</strong> ≥ 0.3 mg/dL above the prior-2-day low</td>
<td>63 (19.5 %)</td>
</tr>
<tr class="even">
<td><code>ckd_incidence</code></td>
<td>Sustained ≥ 90 d: <code>pct_drop &gt; 0.30</code> &amp; eGFR &lt; 60 &amp; baseline eGFR ≥ 60</td>
<td>15 (4.6 %)</td>
</tr>
<tr class="odd">
<td><code>ckd_progression</code></td>
<td>Sustained ≥ 90 d: eGFR &lt; 60 &amp; baseline eGFR &lt; 60</td>
<td>20 (6.2 %)</td>
</tr>
<tr class="even">
<td><code>eskd_defination_1</code></td>
<td>Sustained ≥ 90 d: eGFR &lt; 10</td>
<td>1 (0.3 %)</td>
</tr>
<tr class="odd">
<td><code>esrd_kt_after_ici</code></td>
<td>ESRD / KT / dialysis ICD code after baseline</td>
<td>1 (0.3 %)</td>
</tr>
<tr class="even">
<td><code>eskd_composite</code></td>
<td><code>esrd_kt_after_ici == 1 \| eskd_defination_1 == 1</code></td>
<td>1 (0.3 %)</td>
</tr>
<tr class="odd">
<td><code>ckd_composite</code></td>
<td><code>eskd_composite == 1 \| ckd_incidence == 1 \| ckd_progression == 1</code></td>
<td>35 (10.8 %)</td>
</tr>
</tbody>
</table>
<p>All of the above are <strong>Table 1 rows</strong> on all three analysis pages, together with <code>esrd_kt</code> (ESRD / KT at or before baseline, n = 1), <code>eGFR_CRE_baseline</code>, <code>ckd_stage_baseline</code> and <code>last_cre_days</code>. They also keep a dedicated section — 2.2 on the whole-cohort page, 3.2 on the carboplatin pages — carrying the median time to each event, the length of creatinine follow-up, and the <code>aki</code> vs <code>AKI_kdigo_90days</code> cross-tabulation that Table 1 cannot show.</p>
<p>They are descriptive only: <strong>not</strong> in any Fine-Gray, cause-specific or Cox model, because mixing a full-follow-up outcome into the 90-day competing-risks framework would need its own censoring and competing-event decisions.</p>
<p><code>aki</code> is a different variable from the existing <code>AKI_g2_90days</code> / <code>AKI_kdigo_90days</code>: it compares each creatinine against the patient’s own preceding 90-day median across the whole record, not against a fixed pre-baseline value inside 90 days. In the whole cohort they agree on 19 patients, <code>aki</code> alone flags 44, and <code>AKI_kdigo_90days</code> alone flags 14.</p>
</section>
</section>
<section id="data-sources" class="level1">
<h1>Data Sources</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Used for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>REDCap export <code>CystatinCInPatientsO_DATA_2026-04-27_0819.csv</code></td>
<td>Baseline, treatment, outcomes</td>
</tr>
<tr class="even">
<td>RPDR <strong>2022P001091</strong> (<code>mes98_0728261259…</code>, Aug 2026)</td>
<td><strong>All creatinine</strong> — 48,843 rows</td>
</tr>
<tr class="odd">
<td>RPDR <strong>2026-03-19</strong> (<code>mes98_0318261449…</code>)</td>
<td>HGB, PLT, ALB, GHBA1C (128,156 rows), plus all diagnoses and medications</td>
</tr>
</tbody>
</table>
<p>The newer pull is a creatinine-only extract — it has no <code>Dia</code> or <code>Med</code> file and no HGB/PLT/ALB/GHBA1C — so it supplies creatinine and the original pull supplies everything else. Both cover the same 973 EMPIs over 1989–2026; the newer one has ~2,800 more creatinine values, which is what the longitudinal eGFR, CKD and AKI outcomes are built from.</p>
</section>
<section id="key-variables" class="level1">
<h1>Key Variables</h1>
<section id="exposure" class="level2">
<h2 class="anchored" data-anchor-id="exposure">Exposure</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>egfr_diff_pct</code></td>
<td>100 × (CKD-EPI Cr-Cys unindexed − Cockcroft-Gault) / Cockcroft-Gault</td>
</tr>
<tr class="even">
<td><code>egfr_diff_pct_per10</code></td>
<td>Primary reporting scale: per 10-percentage-point <strong>decline</strong></td>
</tr>
<tr class="odd">
<td><code>egfr_diff_pct_sens_per10</code></td>
<td>Sensitivity: CKD-EPI 2012 CysC vs CKD-EPI 2021 Cr, per 10 % decline</td>
</tr>
<tr class="even">
<td><code>dose_discrep_per25increase</code></td>
<td>Carboplatin dose discrepancy (actual − predicted mg) / 25</td>
</tr>
</tbody>
</table>
</section>
<section id="egfr-kidney-function" class="level2">
<h2 class="anchored" data-anchor-id="egfr-kidney-function">eGFR &amp; Kidney Function</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>baseline_cre_egfr</code></td>
<td>CKD-EPI 2021 creatinine eGFR (mL/min/1.73m²)</td>
</tr>
<tr class="even">
<td><code>ckd_epi_gfr_cre_cys</code></td>
<td>CKD-EPI 2012 combined creatinine + cystatin C eGFR (mL/min/1.73m²)</td>
</tr>
<tr class="odd">
<td><code>ckd_epi_gfr_cre_cys_unindex</code></td>
<td>Combined CKD-EPI eGFR adjusted for BSA (mL/min)</td>
</tr>
<tr class="even">
<td><code>cockcroft</code></td>
<td>Cockcroft-Gault creatinine clearance</td>
</tr>
<tr class="odd">
<td><code>ckd_stage_cre</code></td>
<td>KDIGO G-stage from <code>baseline_cre_egfr</code> (G3a / G3b kept apart)</td>
</tr>
<tr class="even">
<td><code>ckd_stage_cre_cys</code></td>
<td>KDIGO G-stage from <code>ckd_epi_gfr_cre_cys</code> (G3a / G3b kept apart)</td>
</tr>
<tr class="odd">
<td><code>eGFR_CRE_baseline</code></td>
<td>CKD-EPI creatinine eGFR at <code>pre_CRE_45days</code> — the baseline the CKD outcomes are referenced to</td>
</tr>
<tr class="even">
<td><code>ckd_stage_baseline</code></td>
<td>KDIGO stage from <code>eGFR_CRE_baseline</code>, ICI-CKD convention (G3a + G3b collapsed into one stage 3)</td>
</tr>
</tbody>
</table>
<p>Only <code>ckd_epi_gfr_cre_cys_unindex</code> is capped at 125 mL/min; the indexed value and <code>cockcroft</code> are uncapped. Uncapped values feed the eGFR difference; capped values feed the dose-discrepancy calculation.</p>
<p>Both CKD stage variables use the standard KDIGO G categories — G1 ≥ 90, G2 60–89, G3a 45–59, G3b 30–44, G4 15–29, G5 &lt; 15 mL/min/1.73m² — and are built from the <strong>BSA-indexed</strong> eGFRs, the scale KDIGO staging is defined on. No patient in this cohort reaches G5, so that level is dropped rather than shown as an empty Table 1 row. They are descriptive Table 1 rows only; no model adjusts for them (the continuous eGFRs already appear in the adjuster sets).</p>
</section>
<section id="competing-risk-variables" class="level2">
<h2 class="anchored" data-anchor-id="competing-risk-variables">Competing Risk Variables</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pattern</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cmp_time_&lt;outcome&gt;</code></td>
<td>Time for the competing-risk model</td>
</tr>
<tr class="even">
<td><code>cmp_status_&lt;outcome&gt;</code></td>
<td>0 = censored, 1 = event, 2 = death</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="reproducing" class="level1">
<h1>Reproducing</h1>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> <span class="st">"/Users/to909/Desktop/Meg/Cystain C redcap/Ritu project"</span> <span class="kw">&amp;&amp;</span> <span class="ex">quarto</span> render</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>ritu_data.qmd</code> renders first and produces the <code>ritu_final_master.rds</code> that the three analysis pages read. Full project notes are in <code>RITU_PROJECT.md</code>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>